[package]
name                    =  "f429disco"
version                 =  "0.0.1"
description             =  "STM32F429I-DISC1: BSP & REPL in Rust"
authors                 = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license                 =  "MIT"
repository              =  "https://github.com/ponyatov/f429disco"
edition                 =  "2024"

[[bin]]
name                    = "linux"
path                    = "src/linux.rs"
required-features       = ["pc"]

[[bin]]
name                    = "f429disco"
path                    = "src/f429disco.rs"
required-features       = ["f429disco"]

# [lib]
# name                  =  "lib"
# path                  =  "src/lib.rs"

[dependencies]
const_format            = "0.2"
nom                     = { version = "8.0", default-features = false, features = ["alloc"] }

[target.'cfg(all(target_os = "linux"))'.dependencies]
libc                    = "0.2"
memmap2                 = "0.9"

[target.'cfg(all(target_arch = "arm", target_os = "none"))'.dependencies]
cortex-m                = "0.7"
cortex-m-rt             = "0.7"
cortex-m-semihosting    = "0.5"
panic-semihosting       = "0.6"

[features]
# hw
pc                      = ["i5"]
opi800                  = ["rk3399"]
netduinoplus2           = ["stm32f405rg"]
iskra                   = ["stm32f405rg"]
f4disco                 = ["stm32f407vg"]
f429disco               = ["stm32f429zi"]
l496disco               = ["stm32l496ag"]
pillf103                = ["stm32f103c8"]
# cpu
i5                      = ["x86_64"]
rk3399                  = ["aarch64"]
stm32f103c8             = ["stm32f1"]
stm32f405rg             = ["stm32f4"]
stm32f407vg             = ["stm32f4"]
stm32f429zi             = ["stm32f4"]
stm32l496ag             = ["stm32l4"]
# series
stm32f4                 = ["cortexm4"]
stm32l4                 = ["cortexm4"]
# arch
x86_64                  = ["linux"]
aarch64                 = ["linux"]
cortexm                 = ["none"]
cortexm4                = ["cortexm"]
# os
linux                   = []
none                    = []
