include mk/var.mk
include mk/dir.mk
include mk/version.mk
include mk/cross.mk
include mk/tool.mk
include mk/src.mk
include mk/all.mk
include mk/doc.mk
include mk/format.mk
include mk/rule.mk
include mk/rust.mk
include mk/gz.mk
include mk/ref.mk
include mk/install.mk
