[package]
name        =  "server"
version     =  "0.0.1"
description =  "STM32F429I-DISC1: BSP & REPL in Rust /local-host backend/"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license     =  "MIT"
repository  =  "https://github.com/ponyatov/f429disco"
edition     =  "2024"

[[bin]]
path = "src/server.rs"
name = "server"

[dependencies]
config = {path="../config"}
