[package]
name        =  "f429disco-config"
version     =  "0.0.1"
description =  "STM32F429I-DISC1: BSP & REPL in Rust /shared configuration/"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license     =  "MIT"
repository  =  "https://github.com/ponyatov/f429disco"
edition     =  "2024"

[dependencies]
const_format = "0.2"
