[package]
name        =  "f429disco-firmware"
version     =  "0.0.1"
description =  "STM32F429I-DISC1: BSP & REPL in Rust /MCU firmware/"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license     =  "MIT"
repository  =  "https://github.com/ponyatov/f429disco"
edition     =  "2024"

[lib]
path = "src/firmware.rs"
crate-type = ["cdylib"]
name = "firmware"


